"use client";

import {FormEvent,useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {supabase} from "../../../lib/supabase";
import "../admin.css";

export default function SettingsPage(){
 const router=useRouter();
 const[ready,setReady]=useState(false);const[saving,setSaving]=useState(false);const[error,setError]=useState("");const[success,setSuccess]=useState("");
 const[role,setRole]=useState("");
 const[form,setForm]=useState({name:"Banua Research",tagline:"Research · Policy · Regional Insight",location:"Palu, Sulawesi Tengah",email:"halo@banuaresearch.id",instagram:"",linkedin:"",youtube:"",whatsapp:""});
 useEffect(()=>{(async()=>{const{data:{session}}=await supabase.auth.getSession();if(!session){router.replace('/admin/login');return}const[{data:p},{data:rows}]=await Promise.all([supabase.from('profiles').select('role').eq('id',session.user.id).single(),supabase.from('site_settings').select('key,value')]);setRole(p?.role||'');const identity=(rows??[]).find((x:any)=>x.key==='identity')?.value||{};const contact=(rows??[]).find((x:any)=>x.key==='contact')?.value||{};const social=(rows??[]).find((x:any)=>x.key==='social')?.value||{};setForm(v=>({...v,...identity,...contact,...social}));setReady(true)})()},[router]);
 async function save(e:FormEvent){e.preventDefault();setSaving(true);setError('');setSuccess('');try{if(role!=='super_admin')throw new Error('Hanya Super Admin yang dapat mengubah pengaturan situs.');const{data:{session}}=await supabase.auth.getSession();const payloads=[{key:'identity',value:{name:form.name,tagline:form.tagline,location:form.location},updated_by:session?.user.id},{key:'contact',value:{email:form.email,whatsapp:form.whatsapp},updated_by:session?.user.id},{key:'social',value:{instagram:form.instagram,linkedin:form.linkedin,youtube:form.youtube},updated_by:session?.user.id}];const{error}=await supabase.from('site_settings').upsert(payloads,{onConflict:'key'});if(error)throw error;setSuccess('Pengaturan berhasil disimpan.')}catch(err:any){setError(err?.message||'Gagal menyimpan pengaturan.')}finally{setSaving(false)}}
 if(!ready)return <main className="admin-loading">Memuat pengaturan…</main>;
 return <main className="admin-form-page"><div className="admin-form-header"><div><span className="admin-kicker">CMS · SITE SETTINGS</span><h1>Pengaturan</h1><p>Kelola identitas lembaga, kontak publik, dan kanal sosial Banua Research.</p></div><a href="/admin">← Dashboard</a></div><form className="admin-form" onSubmit={save}><div className="admin-form-grid"><label>Nama lembaga<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Lokasi<input value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></label></div><label>Tagline<input value={form.tagline} onChange={e=>setForm({...form,tagline:e.target.value})}/></label><div className="admin-form-grid"><label>Email publik<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>WhatsApp<input value={form.whatsapp} onChange={e=>setForm({...form,whatsapp:e.target.value})} placeholder="contoh: 62812..."/></label></div><div className="admin-form-grid"><label>Instagram<input value={form.instagram} onChange={e=>setForm({...form,instagram:e.target.value})} placeholder="https://instagram.com/..."/></label><label>LinkedIn<input value={form.linkedin} onChange={e=>setForm({...form,linkedin:e.target.value})} placeholder="https://linkedin.com/..."/></label></div><label>YouTube<input value={form.youtube} onChange={e=>setForm({...form,youtube:e.target.value})} placeholder="https://youtube.com/..."/></label>{role!=='super_admin'&&<div className="admin-error">Mode baca saja. Hanya Super Admin yang dapat menyimpan perubahan.</div>}{error&&<div className="admin-error">{error}</div>}{success&&<div className="admin-success">{success}</div>}<div className="admin-form-actions"><button disabled={saving||role!=='super_admin'}>{saving?'Menyimpan...':'Simpan pengaturan'}</button></div></form></main>}
