"use client";

import {FormEvent,useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {supabase} from "../../../lib/supabase";
import "../admin.css";

type MediaItem={path:string;name:string;bucket:string;url:string;created_at?:string|null;metadata?:any};

export default function MediaPage(){
 const router=useRouter();
 const[ready,setReady]=useState(false);const[items,setItems]=useState<MediaItem[]>([]);const[file,setFile]=useState<File|null>(null);const[bucket,setBucket]=useState("public-media");const[loading,setLoading]=useState(false);const[error,setError]=useState("");
 useEffect(()=>{(async()=>{const{data:{session}}=await supabase.auth.getSession();if(!session){router.replace('/admin/login');return}await load();setReady(true)})()},[router]);
 async function load(){const buckets=['public-media','publication-files','researcher-images'];const groups=await Promise.all(buckets.map(async b=>{const{data,error}=await supabase.storage.from(b).list('library',{limit:100,sortBy:{column:'created_at',order:'desc'}});if(error)return[];return (data??[]).filter((x:any)=>x.id).map((x:any)=>{const path=`library/${x.name}`;return{path,name:x.name,bucket:b,url:supabase.storage.from(b).getPublicUrl(path).data.publicUrl,created_at:x.created_at,metadata:x.metadata}})}));setItems(groups.flat())}
 async function upload(e:FormEvent){e.preventDefault();if(!file)return;setLoading(true);setError('');try{const safe=file.name.toLowerCase().replace(/[^a-z0-9._-]+/g,'-');const path=`library/${Date.now()}-${safe}`;const{error}=await supabase.storage.from(bucket).upload(path,file,{upsert:false});if(error)throw error;setFile(null);const input=document.querySelector<HTMLInputElement>('#media-file-input');if(input)input.value='';await load()}catch(err:any){setError(err?.message||'Upload gagal.')}finally{setLoading(false)}}
 async function remove(item:MediaItem){if(!confirm(`Hapus ${item.name}?`))return;const{error}=await supabase.storage.from(item.bucket).remove([item.path]);if(error){setError(error.message);return}await load()}
 if(!ready)return <main className="admin-loading">Memuat media…</main>;
 return <main className="admin-form-page"><div className="admin-form-header"><div><span className="admin-kicker">CMS · STORAGE</span><h1>Media Library</h1><p>Upload, lihat, dan kelola gambar serta PDF yang tersimpan di Supabase Storage.</p></div><a href="/admin">← Dashboard</a></div><form className="admin-form" onSubmit={upload}><div className="admin-form-grid"><label>Tujuan<select value={bucket} onChange={e=>setBucket(e.target.value)}><option value="public-media">Media publik</option><option value="publication-files">PDF publikasi</option><option value="researcher-images">Foto peneliti</option></select></label><label>File<input id="media-file-input" type="file" onChange={e=>setFile(e.target.files?.[0]??null)} required/></label></div>{error&&<div className="admin-error">{error}</div>}<div className="admin-form-actions"><button disabled={loading||!file}>{loading?'Mengunggah...':'Upload file'}</button></div></form><section className="admin-panel" style={{marginTop:20}}><div className="admin-panel-head"><div><span className="admin-kicker">LIBRARY</span><h2>{items.length} file</h2></div></div>{items.length===0?<div className="admin-empty"><h3>Belum ada media.</h3><p>Upload file pertama menggunakan form di atas.</p></div>:<div className="admin-media-grid">{items.map(item=><article className="admin-media-card" key={`${item.bucket}-${item.path}`}><div className="admin-media-preview">{item.metadata?.mimetype?.startsWith('image/')?<img src={item.url} alt={item.name}/>:<span>PDF / FILE</span>}</div><div className="admin-media-meta"><strong>{item.name}</strong><span>{item.bucket}</span><div className="admin-row-actions"><a href={item.url} target="_blank" rel="noreferrer">Buka</a><button type="button" onClick={()=>remove(item)}>Hapus</button></div></div></article>)}</div>}</section></main>}
