"use client";

import {FormEvent,useEffect,useState} from "react";
import {useParams,useRouter} from "next/navigation";
import {supabase} from "../../../../lib/supabase";
import "../../admin.css";

export default function EditResearcherPage(){
 const params=useParams<{id:string}>(); const router=useRouter(); const[ready,setReady]=useState(false); const[loading,setLoading]=useState(false); const[error,setError]=useState(""); const[photo,setPhoto]=useState<File|null>(null); const[currentPhoto,setCurrentPhoto]=useState<string|null>(null);
 const[form,setForm]=useState({name:"",slug:"",title:"",bio:"",expertise:"",email_public:"",linkedin_url:"",orcid:"",is_active:true});
 useEffect(()=>{(async()=>{const{data:{session}}=await supabase.auth.getSession();if(!session){router.replace('/admin/login');return}const{data,error}=await supabase.from('researchers').select('*').eq('id',params.id).single();if(error||!data){setError(error?.message||'Peneliti tidak ditemukan.');setReady(true);return}setCurrentPhoto(data.photo_url);setForm({name:data.name||'',slug:data.slug||'',title:data.title||'',bio:data.bio||'',expertise:Array.isArray(data.expertise)?data.expertise.join('\n'):'',email_public:data.email_public||'',linkedin_url:data.linkedin_url||'',orcid:data.orcid||'',is_active:!!data.is_active});setReady(true)})()},[params.id,router]);
 async function submit(e:FormEvent){e.preventDefault();setLoading(true);setError('');try{let photo_url=currentPhoto;if(photo){const ext=photo.name.split('.').pop()||'jpg';const path=`${form.slug}/${Date.now()}.${ext}`;const{error}=await supabase.storage.from('researcher-images').upload(path,photo);if(error)throw error;photo_url=supabase.storage.from('researcher-images').getPublicUrl(path).data.publicUrl}const{error}=await supabase.from('researchers').update({name:form.name,slug:form.slug,title:form.title||null,bio:form.bio||null,expertise:form.expertise.split('\n').map(x=>x.trim()).filter(Boolean),email_public:form.email_public||null,linkedin_url:form.linkedin_url||null,orcid:form.orcid||null,photo_url,is_active:form.is_active,updated_at:new Date().toISOString()}).eq('id',params.id);if(error)throw error;setCurrentPhoto(photo_url);setPhoto(null);router.push('/admin/researchers')}catch(err:any){setError(err?.message||'Gagal menyimpan peneliti.')}finally{setLoading(false)}}
 if(!ready)return <main className="admin-loading">Memuat profil…</main>;
 return <main className="admin-form-page"><div className="admin-form-header"><div><span className="admin-kicker">EDIT PENELITI</span><h1>{form.name||'Profil peneliti'}</h1><p>Perbarui identitas, bio, keahlian, kontak publik, dan status profil.</p></div><a href="/admin/researchers">← Daftar peneliti</a></div>{error&&<div className="admin-error">{error}</div>}<form className="admin-form" onSubmit={submit}><label>Nama lengkap<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Slug<input required value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/></label><label>Jabatan / posisi<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Bio<textarea rows={7} value={form.bio} onChange={e=>setForm({...form,bio:e.target.value})}/></label><label>Keahlian <small>(satu bidang per baris)</small><textarea rows={5} value={form.expertise} onChange={e=>setForm({...form,expertise:e.target.value})}/></label><div className="admin-form-grid"><label>Email publik<input type="email" value={form.email_public} onChange={e=>setForm({...form,email_public:e.target.value})}/></label><label>ORCID<input value={form.orcid} onChange={e=>setForm({...form,orcid:e.target.value})}/></label></div><label>LinkedIn<input value={form.linkedin_url} onChange={e=>setForm({...form,linkedin_url:e.target.value})}/></label><label>Ganti foto<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>setPhoto(e.target.files?.[0]??null)}/>{currentPhoto&&<a className="admin-file-link" href={currentPhoto} target="_blank">Lihat foto saat ini ↗</a>}</label><label className="admin-check featured"><input type="checkbox" checked={form.is_active} onChange={e=>setForm({...form,is_active:e.target.checked})}/>Profil aktif dan tampil di website</label><div className="admin-form-actions"><a href="/admin/researchers">Batal</a><button disabled={loading}>{loading?'Menyimpan...':'Simpan perubahan'}</button></div></form></main>
}
