"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { supabase } from "../../../lib/supabase";
import "../../globals.css";

type Publication={id:string;title:string;subtitle:string|null;slug:string;publication_type:string;excerpt:string|null;executive_summary:string|null;publication_date:string|null;cover_image_url:string|null;pdf_url:string|null;key_findings:any;recommendations:any;publication_authors?:any[];publication_topics?:any[];publication_regions?:any[]};

export default function PublicationDetail(){
 const params=useParams<{slug:string}>(); const [item,setItem]=useState<Publication|null>(null); const [loading,setLoading]=useState(true);
 useEffect(()=>{if(!params.slug)return;supabase.from("publications").select("id,title,subtitle,slug,publication_type,excerpt,executive_summary,publication_date,cover_image_url,pdf_url,key_findings,recommendations,publication_authors(author_order,researchers(id,name,slug,title)),publication_topics(topics(id,name,slug)),publication_regions(regions(id,name,slug))").eq("slug",params.slug).eq("status","published").maybeSingle().then(({data})=>{setItem(data as any);setLoading(false)})},[params.slug]);
 async function openPdf(){if(!item?.pdf_url)return;await supabase.from('publication_downloads').insert({publication_id:item.id});window.open(item.pdf_url,'_blank','noopener,noreferrer')}
 if(loading)return <main className="section shell"><p>Memuat publikasi...</p></main>;
 if(!item)return <main className="section shell"><h1>Publikasi tidak ditemukan</h1><a href="/publikasi">← Kembali ke publikasi</a></main>;
 const findings=Array.isArray(item.key_findings)?item.key_findings:[]; const recs=Array.isArray(item.recommendations)?item.recommendations:[];
 const authors=(item.publication_authors??[]).slice().sort((a,b)=>(a.author_order??0)-(b.author_order??0)).map(x=>x.researchers).filter(Boolean); const topics=(item.publication_topics??[]).map(x=>x.topics).filter(Boolean); const regions=(item.publication_regions??[]).map(x=>x.regions).filter(Boolean);
 return <main><header className="header"><div className="head shell"><a href="/" className="brand"><img src="https://raw.githubusercontent.com/alurpublik-sys/banuariset/main/public/banua-logo.png" alt="Banua Research"/></a><a href="/publikasi">← Publikasi</a></div><div className="orange"/></header><article className="section shell" style={{maxWidth:980}}><span className="eyebrow">▲ {item.publication_type.replaceAll("_"," ").toUpperCase()}</span><h1 style={{font:"500 54px/1.05 Georgia,serif",margin:"20px 0"}}>{item.title}</h1>{item.subtitle&&<p style={{fontSize:20,color:"#6c7b84",lineHeight:1.5}}>{item.subtitle}</p>}<div className="pub-meta">{item.publication_date&&<span>{item.publication_date}</span>}{authors.length>0&&<span>Oleh {authors.map((a:any,i:number)=><span key={a.id}>{i>0?", ":""}<a href={`/peneliti/${a.slug}`}>{a.name}</a></span>)}</span>}</div>{(topics.length>0||regions.length>0)&&<div className="pub-tags">{topics.map((x:any)=><span key={x.id}>{x.name}</span>)}{regions.map((x:any)=><span key={x.id}>{x.name}</span>)}</div>}{item.cover_image_url&&<img src={item.cover_image_url} alt={item.title} style={{width:"100%",margin:"34px 0"}}/>}<section style={{marginTop:36}}><h2>Ringkasan</h2><p style={{lineHeight:1.8}}>{item.executive_summary||item.excerpt||"Ringkasan publikasi belum tersedia."}</p></section>{findings.length>0&&<section style={{marginTop:36}}><h2>Temuan Utama</h2><ul>{findings.map((x:any,i:number)=><li key={i} style={{marginBottom:12,lineHeight:1.7}}>{typeof x==="string"?x:x?.text||JSON.stringify(x)}</li>)}</ul></section>}{recs.length>0&&<section style={{marginTop:36}}><h2>Rekomendasi</h2><ul>{recs.map((x:any,i:number)=><li key={i} style={{marginBottom:12,lineHeight:1.7}}>{typeof x==="string"?x:x?.text||JSON.stringify(x)}</li>)}</ul></section>}{item.pdf_url&&<button className="cta" style={{border:0,cursor:'pointer'}} onClick={openPdf}>Buka / Download PDF</button>}</article></main>
}
